- geocoder/admin0/README.md
- geocoder/admin0/sql/build_synonym_table.sql
> Updates docs and changes ranks

- README.md
As discussed in https://github.com/CartoDB/website/issues/34#issuecomment-52470498
Closes #114
> Adds disclaimer about disputed boundaries

- geocoder/namedplace/namedplace_country_guessing.sql
@javisantana can you please review?
Just FYI, cc'ing @iriberri
> Add guessing of country for named places #121

- geocoder/namedplace/geocode_namedplace.sql
Almost straight from production db: `\df geocode_namedplace` and `\sf geocode_namedplace(text[], text[])`
cc/ @iriberri
> Add geocode_namedplace functions to source repo

- geocoder/admin0/sql/geocoder.sql
and which are not in the repo
@rafatower
> Adds function that lives in the database adm0

- geocoder/namedplace/sql/geocode_namedplace.sql
@rafatower  I reviewed the old functions which are OK (you added them lately) but this one is living in the database too, so I'm documenting it
> Adds geocode_namedplace_country from db

- geocoder/postal-codes/sql/geocoder.sql
> Uploads functions from database

- geocoder/admin1/sql/geocoder.sql
> Includes admin1 production functions

- geocoder/postal-codes/sql/geocoder.sql
Fixes https://github.com/CartoDB/data-services/issues/173
cc @rafatower
> Updating function for global table

- geocoder/admin0/sql/build_synonym_table.sql
> Fixes adding synonyms for different isocodes

- geocoder/postal-codes/test/data/test.sh
Fixes https://github.com/CartoDB/data-services/issues/179
> Using the tables in production

- geocoder/extension/expected/00_install_test.out
- geocoder/extension/sql/00_install_test.sql
This only affect the tests, so I'm not tagging another RC yet.
@iriberri please review
> Add quota trigger to tests

- common-data/README.md
> Ernesto adds

- geocoder/geocoder_download_dumps
In order to avoid accidental re-downloads of everything
/cc @iriberri
> wget parameter to resume downloads

- common-data/README.md
Natural Earth changed the download links
cc. @talos for awareness, just in case this needs to be fixed in other places.
> fixing naturalearth links

- geocoder/admin0/patches/20160203_countries_bh_isocode.sql
- geocoder/admin0/patches/20160622_countries_synonym_congo.sql
- geocoder/admin0/patches/20180306_add_ssd_rows_for_south_sudan.sql
- geocoder/geocoder_download_patches.sh
> Missing admin0 patches that were in S3 only

- geocoder/admin0/patches/20180306_add_ssd_rows_for_south_sudan.sql
- geocoder/geocoder_download_patches.sh
> Copy South Sudan rows using ISO codes

- geocoder/ip-addresses/README.md
- geocoder/ip-addresses/sql/build_data_table.sql
> IP geocoder table update

- geocoder/carto-package.json
```
{
"dataservices-geocoder-extension": {
"repo_url": "https://github.com/CartoDB/data-services.git",
"tag_format": "{VERSION}",
"manifest": "geocoder/carto-package.json"
}
},
```
cc @lekum
> carto-package.json

- geocoder/carto-package.json
> Changes in component name and semver specification

- geocoder/.gitignore
- geocoder/admin0/patches/20181011_add_synonyms_for_swaziland.sql
- geocoder/geocoder_download_patches.sh
> Add new patch to include new synonyms for Swaziland

- geocoder/geocoder_download_patches.sh
Closes https://github.com/CartoDB/cartodb/issues/14620
> Fix download patches script

- .github/workflows/main.yml
Adds CI tests using github actions
> add CI tests to github actions
